#######################################################################################################################
##   _______   _                      __     __             _    
##  / ___/ /  (_)__  __ _  __ _____  / /__  / /  ___  ___ _(_)___ TM
## / /__/ _ \/ / _ \/  ' \/ // / _ \/  '_/ / /__/ _ \/ _ `/ / __/                  ////  O P E N - S O U R C E ////
## \___/_//_/_/ .__/_/_/_/\_,_/_//_/_/\_\ /____/\___/\_, /_/\__/ 
##           /_/                                    /___/                                    chipmunklogic.com
#######################################################################################################################
# Script           : peqFlash, Pequeno Flasher
# Developer        : Mitu Raj, chip@chipmunklogic.com
# Vendor           : Chipmunk Logic™, https://chipmunklogic.com
#
# Description      : peqFlash is used to flash instruction & data binary files to Pequeno subsystem via 
#                    UART programming IF and boot the system.
#                    >> Binary files  : IMEM & DMEM binary files generated by pqr5asm.
#                    >> Target device : PQR5 v1.0 subsystem
#                    Flags while invoking the script:
#                    -serport <arg>    : Serial port to which the target is connected
#                    -baud <arg>       : Baudrate of serial communication in bps
#                    -imembin <arg>    : IMEM binary file path
#                    -dmembin <arg>    : DMEM binary file path
#                    -reloc <arg>      : [OPTIONAL] Relocates the program to given memory address in IMEM
#                    -cleanimem        : [OPTIONAL] Cleans IMEM with NOP instructions before writing the binary/reboot
#                    -rebootonly       : [OPTIONAL] Overrides input binary files, and reboot with existing binary
#                    Refer to userguide, "Programming_Pequeno_with_peqFlash", for more details. 
#
# Last modified on : August-2024
# Compatiblility   : Python 3.9 tested
#
# Copyright        : Open-source license
#######################################################################################################################
# Import Libraries 
import argparse#解析命令行参数
#操作系统
import sys
import os
import time
import serial#打开com串口

# 全局状态变量
is_reloc = False#是否重定位程序地址
is_ser_open = False#串口是否打开
mytimeout = 10#表示串口读等待 10 秒超时

#定义协议常量
CMD_REQ_DEVC_SIGN = bytes([0xD3])#设备签名请求
CMD_BOOT_REQ_IMEM_CLN = bytes([0xB1])#晴空imem
CMD_BOOT_REQ = bytes([0xB0])#启动
SUCCESS = bytes([0x55])#成功码
ERR_CMD_INVALID = bytes([0xEC])#imem前导码
ERR_PGM = bytes([0xED])#dmem前导码   
ERR_POSTAMBLE = bytes([0xEE])#结束码
DEVC_SIGN = b'\xC0\xDE\x4A\x11'#loader发送的字符串，收到就表示loader正确
IPREAMBLE = b'\xC0\xC0\xC0\xC0'#imem前导码
DPREAMBLE = b'\xD0\xD0\xD0\xD0'#dmem前导码
POSTAMBLE = b'\xE0\xE0\xE0\xE0'#结束标记

# 打印欢迎界面
def print_welcome():
    print('')   
    print("                     _______________               ______  TM  ")      
    print(" ___________________ ___  ____/__  / ______ __________  /_     ")  
    print(" ___  __ \  _ \  __ `/_  /_   __  /  _  __ `/_  ___/_  __ \    ")  
    print(" __  /_/ /  __/ /_/ /_  __/   _  /___/ /_/ /_(__  )_  / / /    ")  
    print(" _  .___/\___/\__, / /_/      /_____/\__,_/ /____/ /_/ /_/     ")  
    print(" /_/            /_/                                            ")
    print("                           - Flasher for Pequeno RISC-V CPU")                    
    print("===============================================================") 
    print(" Chipmunk Logic (TM) 2024")    
    print(" Visit us: chipmunklogic.com")
    print("===============================================================")    
    print('')

# 下载成功打印
def print_pass(): 
    print('')     
    print('______________________________')
    print('___  __ \__    |_  ___/_  ___/')
    print('__  /_/ /_  /| |____ \_____ \ ')
    print('_  ____/_  ___ |___/ /____/ / ')
    print('/_/     /_/  |_/____/ /____/  ')                           
    print('')                                                    
                                                                                                        
# 下载失败打印 
def print_fail(): 
    print('')     
    print('_____________________________  ')       
    print('___  ____/__    |___  _/__  /  ')   
    print('__  /_   __  /| |__  / __  /   ')   
    print('_  __/   _  ___ |_/ /  _  /___ ')   
    print('/_/      /_/  |_/___/  /_____/ ') 
    print('')      

# 成功退出，会打印pass
def exitsucc(isreboot = False):#默认这次不是单纯重启，而是正常下载完成    
    global is_ser_open#全局变量声明
    print_pass()
    if is_ser_open:#判断串口是否打开
        ser.close()#关串口
        is_ser_open = False
        print(f"\nSerial port {ser.name} closed.")
    if not isreboot:#如果不是 reboot-only 模式，就执行下面的打印        
        print("Program upload completed successfully!! :)")    
    exit(0)#正常退出

# 不成功退出，会打印fail
def exitfail():    
    global is_ser_open
    #关串口并打印错误
    if is_ser_open:
        ser.close()
        is_ser_open = False
        print(f"\nSerial port {ser.name} closed.")    
    print('Program upload failed :(')
    print('Exiting with ERROR(s)...')    
    exit(1)#异常退出

# 自定义命令行参数报错时的提示格式
class CustomArgumentParser(argparse.ArgumentParser):#定义一个类
    def error(self, message):#重写 argparse 自带的 error() 函数
        sys.stderr.write(f'\npeqFlash>> [ERROR] {message}\n')#把错误信息输出到标准错误流 stderr，输出错误信息
        sys.stderr.write(f'Usage: python peqflash.py -serport <port> -baud <baudrate> [-imembin <IMEM bin file>] \
[-dmembin <DMEM bin file>] [-reloc <address>] [-cleanimem] [-rebootonly]\n')#打印用法说明，告诉你应该怎么运行这个脚本，纠正错误
        sys.exit(1)#异常退出

# 解析在终端输入的参数，并检查参数是否合法，如：py pequeno.py -serport COM5 -baud 115200 -imembin program_imem.bin -dmembin program_dmem.bin -cleanimem
def parse_arguments():
    global is_reloc#is_reloc 用来记录有没有使用 -reloc 参数（临时修改程序起始地址的参数）
    parser = CustomArgumentParser(description='Pequeno Flasher')#创建一个命令行参数解析器
    #parser = argparse.ArgumentParser(description='Pequeno Flasher')

    # 必需的参数
    parser.add_argument('-serport', required=True, help='Serial port to which the target is connected (e.g., COM1)')#添加一个必选参数，如：-serport COM5表示要打开哪个串口
    parser.add_argument('-baud', required=True, type=int, help='Baudrate of serial communication in bps (e.g., 9600)')#添加一个必选参数 -baud，如：-baud 115200

    # 可选的参数
    parser.add_argument('-imembin', help='IMEM binary file path')  # 添加 -imembin 参数，表示指令 bin 文件路径，如：-imembin program_imem.bin
    parser.add_argument('-dmembin', help='DMEM binary file path')  # 添加 -dmembin 参数，表示数据 bin 文件路径，如：-dmembin program_dmem.bin
    parser.add_argument('-reloc', help='Relocates the program to given memory address in IMEM (0x<addr> or integer)')#用于修改 IMEM 下载包里的 base address，如：-reloc 0x100
    parser.add_argument('-cleanimem', action='store_true', help='Cleans IMEM with NOP instructions before writing the binary')#添加 -cleanimem 参数，如：py pequeno.py ... -cleanimem就会让脚本先通知 loader 清空 IMEM
    parser.add_argument('-rebootonly', action='store_true', help='Overrides input binary files, and reboot with existing binary')#添加 -rebootonly 参数，只要出现它，就表示：不重新下载 bin，只让 CPU 用已有程序重新启动

    args = parser.parse_args()#真正开始解析终端输入的参数，解析完后，结果存在 args 里

    # 检查 -reloc 有没有写空
    if args.reloc is not None and not args.reloc.strip():
        parser.error('peqFlash>> [ERROR] -reloc requires a relocation address.')
        is_reloc = False#如果 -reloc 后面没有地址，就报错，如：-reloc ""
    elif args.reloc is not None:
        is_reloc = True#如果用户确实写了 -reloc 0x...，就把 is_reloc 设为 True

    # 如果不是只重启模式，那就必须下载程序
    if not args.rebootonly:
        #检查imem，dmem文件
        if not args.imembin:
            parser.error('peqFlash>> [ERROR] -imembin is required.')#没imem就报错
        if not args.dmembin:
            parser.error('peqFlash>> [ERROR] -dmembin is required.')#没dmem就报错

    # Additional validation for binary file existence
    if not args.rebootonly:
        #检查用户有没有输入-imembin xxx.bin -dmembin xxx.bin
        is_file_bin = args.imembin.lower().endswith('.bin')   
        if not is_file_bin:
            parser.error(f'peqFlash>> [ERROR] IMEM binary file {args.imembin} is not .bin type')
        is_file_bin = args.dmembin.lower().endswith('.bin')
        if not is_file_bin:
            parser.error(f'peqFlash>> [ERROR] DMEM binary file {args.dmembin} is not .bin type')
        if args.imembin and not os.path.isfile(args.imembin):
            parser.error(f'peqFlash>> [ERROR] IMEM binary file {args.imembin} does not exist!!')
        if args.dmembin and not os.path.isfile(args.dmembin):
            parser.error(f'peqFlash>> [ERROR] DMEM binary file {args.dmembin} does not exist!!')

    return args#把解析好的参数返回给主程序

# 检查.bin文件的格式是否正确
def verify_binary_file(preamble, postamble, bindata):#如：verify_binary_file(IPREAMBLE, POSTAMBLE, imembin_data)
    #preamble   ：期望的开头标志，比如 C0C0C0C0 或 D0D0D0D0
    #postamble  ：期望的结束标志，比如 E0E0E0E0
    #bindata    ：读取进来的整个 bin 文件内容
    # Size of data   
    bindata_bytes = len(bindata)#计算整个 .bin 文件有多少字节

    # 如果文件小于 16 字节，肯定不合法
    #4字节 preamble
    #4字节 program_size
    #4字节 base_addr
    #4字节 postamble
    if bindata_bytes < 16:
        print('File size validation failed')
        return 1
    
    # 检查前 4 个字节是不是正确前导码
    if bindata[0:4] != preamble:        
        print('Preamble validation failed')
        return 1
    
    # 检查后四位是不是结束标记
    if bindata[-4:] != postamble:
        print('Postamble validation failed')
        return 1
    
    # Extract program size and program base address
    program_size = int.from_bytes(bindata[4:8], byteorder='big')#读取第 4 到第 7 字节，把它解释成程序大小
    program_base_addr = int.from_bytes(bindata[8:12], byteorder='big')#读取第 8 到第 11 字节，把它解释成程序写入起始地址

    # 传输的总长度不对
    #4字节 preamble
    #4字节 program_size
    #4字节 base_addr
    #program_size 字节真正数据
    #4字节 postamble
    if bindata_bytes != program_size + 16:
        print('Program size validation failed')
        return 1
    
    #如果都没有报错就报成功
    return 0

# 在终端显示下载进度条的
def display_progress_bar(current, maximum):
    # Calculate the percentage
    percentage = int((current / maximum) * 100)
    
    # Ensure percentage is within valid bounds
    if percentage < 0:
        percentage = 0
    elif percentage > 100:
        percentage = 100
    
    # Use the Unicode solid block character '█'
    progress_char = '█'
    total_slots = 20
    
    # Calculate the number of filled and empty slots
    filled_slots = int((percentage / 100) * total_slots)
    empty_slots = total_slots - filled_slots
    
    # Create the progress bar string
    progress_bar = progress_char * filled_slots + '.' * empty_slots
    
    # Print the progress bar with percentage, overwriting the previous line
    sys.stdout.write(f"{progress_bar} {percentage}%")
    if percentage != 100:
        sys.stdout.flush()
        # Move cursor to the beginning of the line
        sys.stdout.write('\r')
    else:
        print(f' DONE ({current}/{maximum} bytes)')

################################################### MAIN ##############################################################
# Parse & validate arguments
try:
    args = parse_arguments()  
    if is_reloc:          
        unalign_reloc_addr = int(args.reloc, 0)  
        reloc_addr = ((unalign_reloc_addr + 3) // 4) * 4        
        reloc_addr_bytes = reloc_addr.to_bytes(4, byteorder='big', signed=False)
    else:
        reloc_addr = None
except SystemExit as e:  # Catch exit() exception from fn call
    print('\npeqFlash>> Run python peqflash.py --help for more details.')
    print('Exiting with ERROR(s)...')    
    exit(1) 
except (ValueError, OverflowError) as e:
    print('peqFlash>> [ERROR] -reloc has illegal valued argument')
    print('Run python peqflash.py --help for more details.')
    print('Exiting with ERROR(s)...')    
    exit(1)
    
# Store parsed arguments
print('\npeqFlash>> [INFO] Successfully parsed all arguments!!')
print('Launching flasher...')
print_welcome()
serport = args.serport
baud = int(args.baud)
imembin = args.imembin
dmembin = args.dmembin
#reloc_addr already saved
cleanimem = args.cleanimem
rebootonly = args.rebootonly

# Print configuration
print('\nFLASH CONFIGURATION:')
print('')
print(f'{"Serial port":23} {serport}')
print(f'{"Baudrate":23} {baud}')
print(f'{"IMEM binary file":23} {imembin}')
print(f'{"DMEM binary file":23} {dmembin}')
print(f'{"Relocation of program":23} {"YES" if is_reloc else "NO"}')
if is_reloc:
    print(f'{"Relocation address":23} 0x{reloc_addr:08X}')
else:
    print(f'{"Relocation address":23} -')
print(f'{"Clean IMEM":23} {"YES" if cleanimem else "NO"}')
print(f'{"Reboot only":23} {"YES" if rebootonly else "NO"}')
print('')

# Open the serial port and establish the serial communication link
try:
    print("Establishing the communication link...")
    ser = serial.Serial(serport, baud, parity=serial.PARITY_NONE, timeout=mytimeout)
    if ser.is_open:
        is_ser_open = True
        print(f"Serial port {ser.name} opened successfully.")
    else:
        is_ser_open = False
        print(f"Failed to open serial port {ser.name}")            
        sys.exit(1)
except Exception as e:
    print(f"ERROR opening serial port {serport}")
    exitfail()    

#### STEP1: Verify Device signature ####
try:    
    # Send command: Device signature request
    command = CMD_REQ_DEVC_SIGN
    ser.reset_input_buffer()  # Clear the serial buffer first
    ser.write(command)
    print("\nVerifying Device signature...")

    # Wait for the response
    response = ser.read(4)  # Read 4 bytes from the serial port, first byte = MSB of response
    resp_len = len(response)
    if resp_len == 4:
        if response == DEVC_SIGN:
            print(f"Device signature: {response.hex().upper()} verified successfully.")
        else:
            print("Device signature verification failed :(")               
            sys.exit(1)
    else:
        print("Incomplete/no response received, comm. link TIMED OUT!!")   
        print("Device signature verification failed :(")         
        sys.exit(1)
except serial.SerialException as e:
    print(f"\npeqFlash>> [ERROR] Serial port connection lost @{ser.name}!!")     
    exitfail()
except Exception as e:
    exitfail()

#### STEP2: Validation of Binary ####
# Validate binary files if binary loading mode is requested
print("\nValidating the binary files...")
if not rebootonly:
    try:
        # Open the binary files and convert to byte arrays
        f_imembin = open(imembin, "rb")
        imembin_data = bytearray(f_imembin.read())
        f_dmembin = open(dmembin, "rb")
        dmembin_data = bytearray(f_dmembin.read())
    except Exception as e:
        print('Unable to open the binary files.')
        exitfail()

    # Verify the binary file structure
    fbinsts = verify_binary_file(IPREAMBLE, POSTAMBLE, imembin_data)
    if fbinsts:
        print('IMEM binary file validation failed.')
        exitfail()
    print(f'IMEM binary file validation successful, size = {len(imembin_data)} bytes.')
    fbinsts = verify_binary_file(DPREAMBLE, POSTAMBLE, dmembin_data)
    if fbinsts:
        print('DMEM binary file validation failed.')
        exitfail()
    print(f'DMEM binary file validation successful, size = {len(dmembin_data)} bytes.')

#### STEP3: IMEM clean ####
# Perform IMEM clean if IMEM clean slate is requested
if cleanimem:
    try:    
        # Send command: IMEM clean request
        command = CMD_BOOT_REQ_IMEM_CLN
        ser.reset_input_buffer()  # Clear the serial buffer first
        ser.write(command)
        print("\nRequesting IMEM clean...")

        # Wait for the response
        response = ser.read(1)  # Read 1 byte from the serial port, first byte = MSB of response
        resp_len = len(response)
        if resp_len == 1:
            if response == SUCCESS:
                print("IMEM clean done successfully with NOP instructions.")                
            else:
                print("IMEM clean request failed.")               
                sys.exit(1)
        else:
            print("Incomplete/no response received, comm. link TIMED OUT!!")   
            print("IMEM clean request failed.")         
            sys.exit(1)
    except serial.SerialException as e:
        print(f"\npeqFlash>> [ERROR] Serial port connection lost @{ser.name}!!")     
        exitfail()
    except Exception as e:
        exitfail()

# If IMEM clean + reboot only request, nothing further to do...
if cleanimem and rebootonly:
    exitsucc()

# If reboot only request, boot the CPU with existing binary and exit...
if rebootonly:
    try:    
        # Send command: Boot request
        command = CMD_BOOT_REQ
        ser.reset_input_buffer()  # Clear the serial buffer first
        ser.write(command)
        print("\nRequesting reboot...")

        # Wait for the response
        response = ser.read(1)  # Read 1 byte from the serial port, first byte = MSB of response
        resp_len = len(response)
        if resp_len == 1:
            if response == SUCCESS:
                print("Reboot done successfully.")                
            else:
                print("Reboot failed.")               
                sys.exit(1)
        else:
            print("Incomplete/no response received, comm. link TIMED OUT!!")   
            print("Reboot failed.")         
            sys.exit(1)
    except serial.SerialException as e:
        print(f"\npeqFlash>> [ERROR] Serial port connection lost @{ser.name}!!")     
        exitfail()
    except Exception as e:
        exitfail()
    exitsucc(True)  # Nothing further to do...

print("\nPreparing to flash...")

#### STEP4: Flash IMEM ####
# Update the program base address if relocation is requested...
if is_reloc:        
    imembin_data[8] = reloc_addr_bytes[0]
    imembin_data[9] = reloc_addr_bytes[1]
    imembin_data[10] = reloc_addr_bytes[2]
    imembin_data[11] = reloc_addr_bytes[3]

# Send binary
try:
    total_binsize = len(imembin_data)
    prog_binsize = 0    
    print('\nFlashing binary to IMEM:')
    # Iterate over each byte in the data array
    for curr_byte in imembin_data:
        ser.write(bytes([curr_byte]))  # Send each byte
        prog_binsize = prog_binsize + 1
        if prog_binsize % 4 == 0:
            display_progress_bar(prog_binsize, total_binsize)

    # Wait for the response
    response = ser.read(1)  # Read 1 byte from the serial port, first byte = MSB of response
    resp_len = len(response)
    if resp_len == 1:
        if response == SUCCESS:
            print("Flashed successfully.")                
        else:            
            print(f"Flashing failed with ERROR code = 0x{response.hex().upper()}")               
            sys.exit(1)
    else:
        print("Incomplete/no response received, comm. link TIMED OUT!!")  
        print("Flashing failed.")     
        sys.exit(1)
except serial.SerialException as e:
        print(f"\npeqFlash>> [ERROR] Serial port connection lost @{ser.name}!!")     
        exitfail()
except Exception as e:
    exitfail()

#### STEP5: Flash DMEM ####
# Send binary
try:
    total_binsize = len(dmembin_data)
    prog_binsize = 0    
    print('\nFlashing binary to DMEM:')
    # Iterate over each byte in the data array
    for curr_byte in dmembin_data:
        ser.write(bytes([curr_byte]))  # Send each byte
        prog_binsize = prog_binsize + 1
        if prog_binsize % 4 == 0:
            display_progress_bar(prog_binsize, total_binsize)

    # Wait for the response
    response = ser.read(1)  # Read 1 byte from the serial port, first byte = MSB of response
    resp_len = len(response)
    if resp_len == 1:
        if response == SUCCESS:
            print("Flashed successfully.")                
        else:            
            print(f"Flashing failed with ERROR code = 0x{response.hex().upper()}")               
            sys.exit(1)
    else:
        print("Incomplete/no response received, comm. link TIMED OUT!!")  
        print("Flashing failed.")     
        sys.exit(1)
except serial.SerialException as e:
        print(f"\npeqFlash>> [ERROR] Serial port connection lost @{ser.name}!!")     
        exitfail()
except Exception as e:
    exitfail()

#### STEP6: Boot CPU after both memories have been downloaded ####
# 当前 loader 在 C0/D0 下载完成后保持 CPU 复位，需要 B0 才启动。
try:
    time.sleep(0.01)  # 等待 loader 完成上一条 ACK 并返回 IDLE。
    ser.write(CMD_BOOT_REQ)
    print("\nRequesting CPU boot...")
    response = ser.read(1)
    if response != SUCCESS:
        print(f"CPU boot failed: response={response.hex().upper() or 'TIMEOUT'}")
        exitfail()
    print("CPU started successfully.")
except Exception as e:
    print(f"CPU boot error: {e}")
    exitfail()

# COMPLETED flashing and booting the program successfully!
exitsucc()
