#######################################################################################################################
##   _______   _                      __     __             _    
##  / ___/ /  (_)__  __ _  __ _____  / /__  / /  ___  ___ _(_)___ TM
## / /__/ _ \/ / _ \/  ' \/ // / _ \/  '_/ / /__/ _ \/ _ `/ / __/                  ////  O P E N - S O U R C E ////
## \___/_//_/_/ .__/_/_/_/\_,_/_//_/_/\_\ /____/\___/\_, /_/\__/ 
##           /_/                                    /___/                                    chipmunklogic.com
#######################################################################################################################
# Script           : peqFlash, Pequeno Flasher
# Developer        : Mitu Raj, chip@chipmunklogic.com
# Vendor           : Chipmunk Logic™, https://chipmunklogic.com
#
# Description      : peqFlash is used to flash instruction & data binary files to Pequeno subsystem via 
#                    UART programming IF and boot the system.
#                    >> Binary files  : IMEM & DMEM binary files generated by pqr5asm.
#                    >> Target device : PQR5 v1.0 subsystem
#                    Flags while invoking the script:
#                    -serport <arg>    : Serial port to which the target is connected
#                    -baud <arg>       : Baudrate of serial communication in bps
#                    -imembin <arg>    : IMEM binary file path
#                    -dmembin <arg>    : DMEM binary file path
#                    -reloc <arg>      : [OPTIONAL] Relocates the program to given memory address in IMEM
#                    -cleanimem        : [OPTIONAL] Cleans IMEM with NOP instructions before writing the binary/reboot
#                    -rebootonly       : [OPTIONAL] Overrides input binary files, and reboot with existing binary
#                    Refer to userguide, "Programming_Pequeno_with_peqFlash", for more details. 
#
# Last modified on : August-2024
# Compatiblility   : Python 3.9 tested
#
# Copyright        : Open-source license
#######################################################################################################################
# Adapted for this project's 32 KiB IRAM/DRAM and separate CPU print UART.
import argparse
import codecs
from contextlib import ExitStack
from pathlib import Path
import sys
import time

# 根目录存放镜像打包工具；无论从哪个工作目录调用都使用同一份工具。
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pack_flash import REGION_BYTES, make_image

CMD_REQ_DEVC_SIGN = b"\xD3"
CMD_BOOT_REQ_IMEM_CLN = b"\xB1"
CMD_BOOT_REQ = b"\xB0"
SUCCESS = b"\x55"
DEVC_SIGN = bytes.fromhex("c0de4a11")
IPREAMBLE = b"\xC0" * 4
DPREAMBLE = b"\xD0" * 4
POSTAMBLE = b"\xE0" * 4
ERRORS = {0xEC: "invalid command", 0xED: "programming error",
          0xEE: "invalid postamble"}


def verify_binary_file(preamble, postamble, bindata):
    """Return 0 for a valid 32 KiB loader frame, 1 otherwise."""
    if len(bindata) < 16 or bindata[:4] != preamble or bindata[-4:] != postamble:
        return 1
    size = int.from_bytes(bindata[4:8], 'big')
    offset = int.from_bytes(bindata[8:12], 'big')
    return int(len(bindata) != size + 16 or size % 4 != 0 or offset % 4 != 0
               or offset >= REGION_BYTES or offset + size > REGION_BYTES)


def prepare_image(path, preamble, raw=False, offset=None):
    data = Path(path).read_bytes()
    if raw:
        data = make_image(data, preamble[0], 0 if offset is None else offset)
    else:
        # Validate the original frame before optionally relocating it.
        if verify_binary_file(preamble, POSTAMBLE, data):
            raise ValueError(f"{path}: invalid frame, alignment, or 32 KiB size; use --raw for raw binaries")
        if offset is not None:
            data = data[:8] + offset.to_bytes(4, 'big') + data[12:]
    if verify_binary_file(preamble, POSTAMBLE, data):
        raise ValueError(f"{path}: image/offset exceeds the 32 KiB region or is unaligned")
    return data


def parse_arguments(argv=None):
    parser = argparse.ArgumentParser(description='CPU UART downloader and separate print-port monitor')
    parser.add_argument('-serport', '--port', dest='serport', required=True, help='loader serial port')
    parser.add_argument('-baud', '--baud', type=int, default=115200, help='loader baud (default: 115200)')
    parser.add_argument('-imembin', '--imem', dest='imembin', help='instruction loader frame (.bin)')
    parser.add_argument('-dmembin', '--dmem', dest='dmembin', help='data loader frame (.bin)')
    parser.add_argument('-reloc', type=lambda value: int(value, 0), help='IMEM offset; CPU still boots at 0')
    parser.add_argument('-cleanimem', action='store_true', help='send B1 to fill IRAM with NOP before downloading')
    parser.add_argument('-rebootonly', action='store_true', help='boot existing RAM contents without downloading')
    parser.add_argument('--raw', action='store_true', help='input files are little-endian raw binaries')
    parser.add_argument('--demo', action='store_true', help='download existing build/led_uart/*.flash.bin; run make with LLVM first')
    parser.add_argument('--timeout', type=float, default=10, help='loader transaction timeout in seconds')
    parser.add_argument('--monitor-port', help='separate CPU print serial port; opened before CPU boot')
    parser.add_argument('--monitor-baud', type=int, default=115200, help='CPU_UART_BPS (default: 115200)')
    parser.add_argument('--monitor-seconds', type=float, default=0, help='monitor duration; 0 = until Ctrl+C')
    args = parser.parse_args(argv)
    if args.baud <= 0 or args.monitor_baud <= 0 or args.timeout <= 0 or args.monitor_seconds < 0:
        parser.error('baud/timeout must be positive and monitor duration nonnegative')
    if args.monitor_port and args.monitor_port == args.serport:
        parser.error('--monitor-port must be the independent CPU UART port, not the loader port')
    if args.monitor_seconds and not args.monitor_port:
        parser.error('--monitor-seconds requires --monitor-port')
    if args.demo and (args.imembin or args.dmembin or args.raw or args.rebootonly or args.reloc is not None):
        parser.error('--demo cannot be combined with binary paths, --raw, -rebootonly or -reloc')
    if not args.demo and not args.rebootonly and not (args.imembin and args.dmembin):
        parser.error('provide -imembin and -dmembin, or use --demo / -rebootonly')
    if args.reloc is not None and (args.reloc < 0 or args.reloc >= REGION_BYTES or args.reloc % 4):
        parser.error('-reloc must be a 4-byte aligned offset within 32 KiB')
    return args


def write_all(port, data):
    sent = 0
    while sent < len(data):
        count = port.write(data[sent:])
        if not count:
            raise RuntimeError('serial write made no progress')
        sent += count


def read_exact(port, count, timeout):
    deadline = time.monotonic() + timeout
    result = bytearray()
    old_timeout = port.timeout
    try:
        while len(result) < count:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(f'expected {count} response bytes, received {len(result)}')
            port.timeout = remaining
            result.extend(port.read(count - len(result)))
    finally:
        port.timeout = old_timeout
    return bytes(result)


def expect_success(port, timeout, operation):
    response = read_exact(port, 1, timeout)
    if response != SUCCESS:
        reason = ERRORS.get(response[0], 'unexpected response')
        raise RuntimeError(f'{operation}: {reason} (0x{response[0]:02X})')
    # The RTL samples ACK completion a few cycles after the physical stop bit.
    time.sleep(0.01)
    print(f'{operation}: OK')


def monitor(port, seconds):
    print(f'CPU output on {port.name}; Ctrl+C to stop', flush=True)
    decoder = codecs.getincrementaldecoder('utf-8')(errors='replace')
    deadline = time.monotonic() + seconds if seconds else None
    port.timeout = 0.1
    try:
        while deadline is None or time.monotonic() < deadline:
            data = port.read(max(1, min(port.in_waiting, 4096)))
            if data:
                print(decoder.decode(data), end='', flush=True)
    except KeyboardInterrupt:
        print('\nMonitor stopped.')
    finally:
        print(decoder.decode(b'', final=True), end='', flush=True)


def main(argv=None):
    args = parse_arguments(argv)
    try:
        # LLVM 编译由 make 完成，下载脚本只读取镜像；打开串口前先检查文件。
        if args.demo:
            args.imembin = ROOT / 'build/led_uart/imem.flash.bin'
            args.dmembin = ROOT / 'build/led_uart/dmem.flash.bin'
            if not args.imembin.is_file() or not args.dmembin.is_file():
                raise ValueError('Demo images not found: run make in the project root first (make ACTIVE_LOW=1 for active-low LEDs)')
            print(f'Demo images: {args.imembin}, {args.dmembin}')
        if not args.rebootonly:
            imem = prepare_image(args.imembin, IPREAMBLE, args.raw, args.reloc)
            dmem = prepare_image(args.dmembin, DPREAMBLE, args.raw)
        try:
            import serial
        except ImportError:
            raise RuntimeError('pyserial is required: python3 -m pip install pyserial') from None

        with ExitStack() as stack:
            print_port = None
            if args.monitor_port:
                # Open early so even the first CPU byte is buffered before B0 ACK.
                print_port = serial.Serial(args.monitor_port, args.monitor_baud,
                                           timeout=0.1, write_timeout=args.timeout)
                stack.callback(print_port.close)
                print_port.reset_input_buffer()
            port = serial.Serial(args.serport, args.baud, timeout=args.timeout,
                                 write_timeout=args.timeout)
            stack.callback(port.close)
            port.reset_input_buffer()
            write_all(port, CMD_REQ_DEVC_SIGN)
            if read_exact(port, 4, args.timeout) != DEVC_SIGN:
                raise RuntimeError('device signature mismatch')
            time.sleep(0.01)
            print('Device signature: C0DE4A11')

            if args.cleanimem:
                write_all(port, CMD_BOOT_REQ_IMEM_CLN)
                expect_success(port, args.timeout, 'Clear IRAM')
            if not args.rebootonly:
                for name, data in (('IRAM', imem), ('DRAM', dmem)):
                    write_all(port, data)
                    expect_success(port, args.timeout, f'Download {name} ({len(data)-16} bytes)')
            # B1 already boots after cleaning when used with -rebootonly.
            if not (args.cleanimem and args.rebootonly):
                write_all(port, CMD_BOOT_REQ)
                expect_success(port, args.timeout, 'Boot CPU')
            print('CPU started. Printing uses cpu_uart_txd, not the loader TX pin.')
            if print_port is not None:
                # Do not reset this buffer after boot: early messages must survive.
                monitor(print_port, args.monitor_seconds)
        return 0
    except KeyboardInterrupt:
        print('\nDownload interrupted.', file=sys.stderr)
        return 130
    except Exception as error:
        print(f'peqFlash: {error}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
