`include "define.sv"

// Memory stage with a native data-memory request/response port.
module mem_stage(
    input  wire                clk,
    input  wire                rst_n,
    input  wire                reg_we_i,
    input  wire [`RegAddrBus]  rd_i,
    input  wire [`WbSelBus]   wb_sel_i,
    input  wire [`RegBus]     alu_result_i,
    input  wire [`RegBus]     store_data_i,
    input  wire                mem_re_i,
    input  wire                mem_we_i,
    input  wire [`MemOpBus]   mem_op_i,
    input  wire [`InstAddrBus] pc_plus4_i,
    input  wire                fence_i,
    input  wire                csr_we_i,
    input  wire [`CsrAddrBus] csr_waddr_i,
    input  wire [`CsrDataBus] csr_wdata_i,
    input  wire                load_flag_i,
    output wire [`RegBus]     alu_result_o,
    output wire [`InstAddrBus] pc_plus4_o,
    output wire [`RegAddrBus] rd_o,
    output wire                reg_we_o,
    output wire [`DataBus]    mem_data_o,
    output wire [`WbSelBus]   wb_sel_o,
    output wire                load_flag_o,
    output wire                fence_o,
    output wire                csr_we_o,
    output wire [`CsrAddrBus] csr_waddr_o,
    output wire [`CsrDataBus] csr_wdata_o,
    input  wire                mem_accept_i,
    output wire                mem_req_o,
    output wire [`ByteWidth]  uart_tx_data,
    output wire                uart_tx_valid,
    input  wire                uart_tx_ready,
    input  wire                uart_rsp_valid,
    input  wire                uart_rsp_error,
    output wire                dmem_req_valid,
    input  wire                dmem_req_ready,
    output wire [`DataAddrBus] dmem_req_addr,
    output wire [`DataBus]    dmem_req_wdata,
    output wire [3:0]          dmem_req_wstrb,
    output wire                dmem_req_write,
    input  wire                dmem_rsp_valid,
    input  wire [`DataBus]    dmem_rsp_rdata,
    output wire                mmio_req_valid,
    input  wire                mmio_req_ready,
    output wire [`DataAddrBus] mmio_req_addr,
    output wire [`DataBus]    mmio_req_wdata,
    output wire [3:0]          mmio_req_wstrb,
    output wire                mmio_req_write,
    input  wire                mmio_rsp_valid,
    output wire                mmio_rsp_ready,
    input  wire [`DataBus]    mmio_rsp_rdata
);

assign csr_we_o    = csr_we_i;
assign csr_waddr_o = csr_waddr_i;
assign csr_wdata_o = csr_wdata_i;

mem u_mem (
    .clk               (clk),
    .rst_n             (rst_n),
    .reg_we_i          (reg_we_i),
    .rd_i              (rd_i),
    .wb_sel_i          (wb_sel_i),
    .alu_result_i      (alu_result_i),
    .store_data_i      (store_data_i),
    .mem_re_i          (mem_re_i),
    .mem_we_i          (mem_we_i),
    .mem_op_i          (mem_op_i),
    .pc_plus4_i        (pc_plus4_i),
    .fence_i           (fence_i),
    .load_flag_i       (load_flag_i),
    .alu_result_o      (alu_result_o),
    .pc_plus4_o        (pc_plus4_o),
    .rd_o              (rd_o),
    .reg_we_o          (reg_we_o),
    .mem_data_o        (mem_data_o),
    .wb_sel_o          (wb_sel_o),
    .load_flag_o       (load_flag_o),
    .fence_o           (fence_o),
    .mem_accept_i      (mem_accept_i),
    .mem_req_o         (mem_req_o),
    .dbg_uart_tx_data  (uart_tx_data),
    .dbg_uart_tx_valid (uart_tx_valid),
    .dbg_uart_tx_ready (uart_tx_ready),
    .dbg_rsp_valid     (uart_rsp_valid),
    .dbg_rsp_ready     (),
    .dbg_rsp_error     (uart_rsp_error),
    .debug_load_start  (),
    .debug_read_word   (),
    .mem_req_valid     (dmem_req_valid),
    .mem_req_ready     (dmem_req_ready),
    .mem_req_addr      (dmem_req_addr),
    .mem_req_wdata     (dmem_req_wdata),
    .mem_req_wstrb     (dmem_req_wstrb),
    .mem_req_write     (dmem_req_write),
    .mem_rsp_valid     (dmem_rsp_valid),
    .mem_rsp_rdata     (dmem_rsp_rdata),
    .mmio_req_valid    (mmio_req_valid),
    .mmio_req_ready    (mmio_req_ready),
    .mmio_req_addr     (mmio_req_addr),
    .mmio_req_wdata    (mmio_req_wdata),
    .mmio_req_wstrb    (mmio_req_wstrb),
    .mmio_req_write    (mmio_req_write),
    .mmio_rsp_valid    (mmio_rsp_valid),
    .mmio_rsp_ready    (mmio_rsp_ready),
    .mmio_rsp_rdata    (mmio_rsp_rdata)
);

endmodule
